#!/bin/bash

error=`tput setaf 1`
green=`tput setaf 2`
file=`tput setaf 4`
reset=`tput sgr 0`

success=0
if [ -e $1 ] && [ ! -w $1 ]; then
	echo "${error}Brak praw do zapisu do pliku: ${file}$1 ${reset}"
	exit 1
else
	if [ ! -e $1 ]; then
	echo "${green}Plik: ${file}$1 ${green}nie istnieje, wiec zostanie stworzony ${reset}"
	fi
fi
	for (( i = 2; i <= $# ; i++)); do
			plik=${!i}
			#sprawdzenie czy plik istnieje
			if [ -e $plik ]; then
				#sprawdzenie czy mamy prawa do odczytu
					if [ -w $plik ]; then
						#sprawdzenie czy plik nie jest pusty
						if [ -s $plik ]; then
							#sprawdzenie czy plik jest zwykły
							if [ -f $plik ]; then
								cat ${!i} >> $1
								((success++))
							else	
								echo "${error}Plik: ${file}${!i} ${error}nie jest zwyklym plikiem${reset}"
								exit 1
							fi
						else
							echo "${error}Plik: ${file}${!i} ${error} jest pusty${reset}"
							exit 1
						fi
				else
					echo "${error}Brak prawa do odczytu pliku: ${file}${!i}${reset}"
					exit 1
				fi
			else
				echo "${error}Plik ${file}${!i} ${error}nie istnieje${reset}"
				exit 1
			fi
	done
if [ $success -ge 1 -a $success -le 4 ];then
	echo "${green}Udalo sie polaczyc $success pliki do pliku: ${file}$1${reset}"
else
	echo "${green}Udalo sie polaczyc $success plikow do pliku: ${file}$1${reset}"
fi
