#!/bin/bash
success=0 #ilosc pomyslnie dodanych uzytkownikow
fail=0		#ilosc niepomyslnie dodanych uzytkownikow
error=`tput setaf 1`
green=`tput setaf 2`
user=`tput setaf 4`
reset=`tput sgr 0`

for i in $@ ; do
	test=$(cut -f 1 -d ":" /etc/passwd | grep $i)
	if [ -n "${test}" ]
		then
			echo "${error}Uzytkownik ${user}$i${error} jest juz w systemie${reset}"
			((fail+=1))
		else
			sudo useradd $i -m
			echo $i:$i | sudo chpasswd
			sudo passwd $i -e 1>/dev/null
			echo "${green}Uzytkownik ${user}$i${green} zostal dodany do systemu${reset}"
			((success+=1))
	fi
done
if [ $success -ge 1 ] && [ $fail -eq 0 ] ; then
	echo "${green}Pomyslnie dodano $succes uzytkownikow${reset}"
	echo "Haslo do konta jest takie samo jak login"
	echo "Po zalogowaniu uzytkownicy zostana poproszeni o zmiane hasla"
elif [ $success -eq 0 ] ; then
	echo "${error}Nie dodano zadnego uzytkownika${reset}"
else
	echo "${green}Pomyslnie dodanych uzytkownikow: $succes ${reset}"
	echo "${error}Niepomyslnie dodanych uzytkownikow: $fail ${reset}"
	echo "Haslo do konta jest takie samo jak login"
	echo "Po zalogowaniu uzytkownicy zostana poproszeni o zmiane hasla"
fi
